<a href="https://colab.research.google.com/github/prit-patel2003/Pytorch-NoteBook/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print(f"cuda is available {torch.cuda.get_device_name(0)}")
else:
    print("cuda is not available")

cuda is available Tesla T4


In [4]:
torch.empty(size=(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
b=torch.rand(3,2)
b

tensor([[0.6869, 0.1409],
        [0.5217, 0.0252],
        [0.5093, 0.9279]])

In [9]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.dtype

torch.int64

In [10]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [14]:
torch.eye(5)
torch.diag(torch.tensor([1,2,3,4,5]))

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])

In [ ]:
torch.full((3,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [ ]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068092717642034485, 3977023954685147440, 6500437225324819246]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5533, 0.8889, 0.6380],
        [0.0725, 0.1009, 0.8115]])

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
print(x+2)
print(x-2)
print(x*2)
print(x/2)
print((x*100)//3)
print(((x*100)//3)%2)
print(x**2)


tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0,  1],
        [ 2,  3,  4]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[ 33,  66, 100],
        [133, 166, 200]])
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [ ]:
e=torch.randint(size=(2,3),low=0,high=20,dtype=torch.float32)
e

tensor([[11., 19., 13.],
        [14.,  0.,  4.]])

In [ ]:
torch.sum(e)


tensor(61.)

In [ ]:
torch.sum(e,dim=0)

tensor([25., 19., 17.])

In [ ]:
torch.sum(e,dim=1)


tensor([43., 18.])

In [ ]:
torch.mean(e)

tensor(10.1667)

In [ ]:
torch.median(e)

tensor(11.)

In [ ]:
torch.mode(e)

torch.return_types.mode(
values=tensor([11.,  0.]),
indices=tensor([0, 1]))

In [ ]:
torch.max(e)

tensor(19.)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(6.9690)

In [ ]:
torch.var(e)

tensor(48.5667)

In [ ]:
torch.argmax(e)
# max in E position

tensor(1)

In [ ]:
torch.argmin(e)
# min in E position

tensor(4)

In [ ]:
torch.matmul(e,b)

tensor([[ 8.9335, 28.7845],
        [ 1.2406,  9.7283]])

In [ ]:
# need same matrix
# torch.dot(e,b)

In [ ]:
 torch.transpose(e,1,0)

tensor([[11., 14.],
        [19.,  0.],
        [13.,  4.]])

In [ ]:
# torch.det(e)
# need same type matrix

In [ ]:
m=torch.randint(size=(2,3),low=0,high=10)
n=torch.randint(size=(2,3),low=0,high=10)

m

tensor([[0, 4, 4],
        [6, 1, 1]])

In [ ]:
m.add_(n)
m
# _ for inplace

tensor([[ 0, 10,  7],
        [ 9,  5,  9]])

In [ ]:
a=torch.randint(size=(2,3),low=0,high=10)
b=a


In [ ]:
id(a)

133156820983760

In [ ]:
id(b)

133156820983760

In [ ]:
b=a.clone()

In [ ]:
id(a)

133156820983760

In [ ]:
id(b)

133153395237200

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand((2,3),device=device)

tensor([[0.4365, 0.7032, 0.4331],
        [0.1266, 0.7861, 0.3063]], device='cuda:0')

In [ ]:
a=torch.rand((2,3))

In [ ]:
d=a.to(device)

In [ ]:
d+5

tensor([[5.5945, 5.9365, 5.9929],
        [5.4689, 5.7879, 5.4751]], device='cuda:0')

In [ ]:
import time

size=10000

m1=torch.randn(size,size)
m2=torch.randn(size,size)

start_time=time.time()
result_cpu=torch.matmul(m1,m2)
cpu_time=time.time()-start_time
print(f"cpu time {cpu_time}")

m1=m1.to(device)
m2=m2.to(device)

start_time=time.time()
result_gpu=torch.matmul(m1,m2)
gpu_time=time.time()-start_time

print(f"gpu time {gpu_time}")
print(f"cpu/gpu time {cpu_time/gpu_time}")


cpu time 24.82835865020752
gpu time 0.19814443588256836
cpu/gpu time 125.30434447789497


In [ ]:
a.reshape(3,2)

tensor([[0.5945, 0.9365],
        [0.9929, 0.4689],
        [0.7879, 0.4751]])

In [ ]:
a.flatten()

tensor([0.5945, 0.9365, 0.9929, 0.4689, 0.7879, 0.4751])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.9989, 0.4696, 0.2238, 0.6151],
         [0.2159, 0.4753, 0.3225, 0.4754],
         [0.4257, 0.0580, 0.1185, 0.0736]],

        [[0.4967, 0.1688, 0.5754, 0.7087],
         [0.3608, 0.5413, 0.9950, 0.7519],
         [0.7383, 0.1499, 0.4781, 0.1849]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c

tensor([[[0.7912, 0.1356, 0.6007],
         [0.9008, 0.8607, 0.1145],
         [0.9973, 0.2797, 0.9481],
         ...,
         [0.5587, 0.5117, 0.0216],
         [0.6906, 0.4162, 0.5104],
         [0.7757, 0.7447, 0.1616]],

        [[0.9318, 0.8180, 0.0954],
         [0.2691, 0.2382, 0.5332],
         [0.6114, 0.6005, 0.7901],
         ...,
         [0.1799, 0.8145, 0.1593],
         [0.6971, 0.5813, 0.5842],
         [0.5369, 0.1580, 0.7742]],

        [[0.4551, 0.4632, 0.0739],
         [0.3345, 0.5974, 0.4928],
         [0.6379, 0.7063, 0.5114],
         ...,
         [0.9264, 0.1343, 0.7753],
         [0.5363, 0.5505, 0.3863],
         [0.8405, 0.3469, 0.1008]],

        ...,

        [[0.0650, 0.7668, 0.5224],
         [0.3855, 0.6410, 0.6233],
         [0.7998, 0.2434, 0.0687],
         ...,
         [0.4050, 0.2718, 0.3607],
         [0.5681, 0.9986, 0.1322],
         [0.3770, 0.3545, 0.7284]],

        [[0.9494, 0.2939, 0.1378],
         [0.0368, 0.8654, 0.5310],
         [0.

In [ ]:
#Diffrentitation AutoGrad
x=torch.tensor(3.0,requires_grad=True)
y=x**2
y.backward()
x.grad

tensor(6.)

In [ ]:
x=torch.tensor(4.0,requires_grad=True)
y=x**2
z=torch.sin(y)
z.backward()
x.grad

tensor(-7.6613)

In [ ]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred=torch.sigmoid(z)

In [ ]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8
  prediction=torch.clamp(prediction,min=epsilon,max=1-epsilon)
  loss=-(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()


In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
x=torch.tensor([1,2,3],requires_grad=True,dtype=torch.float32)
y=(x**2).mean()
y.backward()
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
  import pandas as pd
  import numpy as np
  from sklearn.model_selection import train_test_split as tts
  from sklearn.preprocessing import StandardScaler
  from sklearn.preprocessing import LabelEncoder


In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [ ]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [ ]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [ ]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
X=df.drop('diagnosis',axis=1)
Y=df['diagnosis']



In [ ]:
df.shape

(569, 31)

In [ ]:
X_train,X_test,Y_train,Y_test=tts(X,Y,random_state=42,test_size=0.1)
Scaler=StandardScaler()
X_train=Scaler.fit_transform(X_train)
X_test=Scaler.transform(X_test)

In [ ]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.fit_transform(Y_test)

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
Y_train_tensor=torch.from_numpy(Y_train)
X_test_tensor=torch.from_numpy(X_test)
Y_test_tensor=torch.from_numpy(Y_test)
X_train.dtype


dtype('float64')

In [ ]:
class Simple_Neural_network():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    return torch.sigmoid(torch.matmul(X,self.weights)+self.bias)

  def loss_function(self,prediction,target):
    epsilon=1e-7
    prediction=torch.clamp(prediction,min=epsilon,max=1-epsilon)
    loss=-(target*torch.log(prediction)+(1-target)*torch.log(1-prediction)).mean()
    return loss

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
model=Simple_Neural_network(X_train_tensor)
model.weights

tensor([[0.2638],
        [0.1834],
        [0.8964],
        [0.4200],
        [0.9442],
        [0.6334],
        [0.3563],
        [0.7322],
        [0.0393],
        [0.9813],
        [0.9618],
        [0.5113],
        [0.5024],
        [0.2962],
        [0.3284],
        [0.4616],
        [0.8720],
        [0.5847],
        [0.5618],
        [0.0855],
        [0.2054],
        [0.5204],
        [0.7028],
        [0.5042],
        [0.0059],
        [0.1086],
        [0.6309],
        [0.7312],
        [0.8356],
        [0.1213]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
for i in range(epochs):
  y_pred=model.forward(X_train_tensor)
  loss=model.loss_function(y_pred,Y_train_tensor)
  loss.backward()

  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"loss  {i+1} {loss.item()}")




loss  1 0.6732744423607526
loss  2 0.6732158812403629
loss  3 0.6731580010146485
loss  4 0.6731007900058779
loss  5 0.6730442368363385
loss  6 0.67298833041712
loss  7 0.6729330599374236
loss  8 0.6728784148543703
loss  9 0.6728243848832829
loss  10 0.6727709599884152
loss  11 0.6727181303741079
loss  12 0.6726658864763447
loss  13 0.6726142189546933
loss  14 0.6725631186846068
loss  15 0.6725125767500709
loss  16 0.6724625844365748
loss  17 0.6724131332243957
loss  18 0.6723642147821733
loss  19 0.672315820960768
loss  20 0.6722679437873793
loss  21 0.6722205754599224
loss  22 0.6721737083416384
loss  23 0.6721273349559367
loss  24 0.6720814479814514
loss  25 0.6720360402473042


In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==Y_test_tensor).float().mean()
  print(f"accuracy {accuracy.item()}")

accuracy 0.6946752667427063
